//
// File generated by rootcint at Mon Oct 16 16:00:58 2023

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME libDiffAnalysis_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "libDiffAnalysis_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

/********************************************************
* libDiffAnalysis_Dict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablelibDiffAnalysis_Dict();

extern "C" void G__set_cpp_environmentlibDiffAnalysis_Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("./DiffJetXFCalcRun17_WestRP.h");
  G__add_compiledheader("./AnRunDiffJetTreeMakerrun17RPFMS_zerobias.h");
  G__add_compiledheader("./DiffJetXFCalcRun17.h");
  G__add_compiledheader("./DiffJetGetRunList.h");
  G__add_compiledheader("./AnRunDiffJetTreeMakerGetBBC.h");
  G__add_compiledheader("./AnRunDiffJetTreeMakerrun17RPFMS.h");
  G__add_compiledheader("./DiffJetRPFMSCorr.h");
  G__add_compiledheader("./DiffJetAnaTreeQaRun17.h");
  G__add_compiledheader("./DiffJetXFANCalc_4pt.h");
  G__add_compiledheader("./AnRunEEMCpi0RpTreeMaker.h");
  G__add_compiledheader("./DiffJetXFANCalc_12np_5pt.h");
  G__add_compiledheader("./AnRunDiffJetTreeMaker.h");
  G__add_compiledheader("./DiffJetAnaTreeQa.h");
  G__add_compiledheader("./DiffJetXFANCalc_12np_4pt_bkg.h");
  G__add_compiledheader("./AnRunFmsPi0RpTreeMaker.h");
  G__add_compiledheader("./DiffJetXFANCalc_12np_7pt.h");
  G__add_compiledheader("./DiffJetXFANCalc_4pt_bkg.h");
  G__add_compiledheader("./DiffJetXFANCalc.h");
  G__add_compiledheader("./DiffJetRpCheck.h");
  G__add_compiledheader("./AnRunDiffJetTreeMakerrun17RPEEMC.h");
  G__add_compiledheader("./DiffJetXFCalc.h");
  G__add_compiledheader("./DiffJetXFANCalc_5pt.h");
  G__add_compiledheader("./DiffJetXFANCalc_12np_4pt.h");
  G__add_compiledheader("./AnRun17RPTreeMaker.h");
  G__cpp_reset_tagtablelibDiffAnalysis_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevlibDiffAnalysis_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Setting up global function */
static int G__libDiffAnalysis_Dict__0_2286(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      DiffJetXFCalcRun17_WestRP(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3])));
      G__setnull(result7);
      break;
   case 3:
      DiffJetXFCalcRun17_WestRP(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      DiffJetXFCalcRun17_WestRP(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      DiffJetXFCalcRun17_WestRP(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2287(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 5:
      AnRunDiffJetTreeMakerrun17RPFMS_zerobias(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3]))
, (Bool_t) G__int(libp->para[4]));
      G__setnull(result7);
      break;
   case 4:
      AnRunDiffJetTreeMakerrun17RPFMS_zerobias(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3])));
      G__setnull(result7);
      break;
   case 3:
      AnRunDiffJetTreeMakerrun17RPFMS_zerobias(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      AnRunDiffJetTreeMakerrun17RPFMS_zerobias(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      AnRunDiffJetTreeMakerrun17RPFMS_zerobias(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   case 0:
      AnRunDiffJetTreeMakerrun17RPFMS_zerobias();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2288(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      DiffJetXFCalcRun17(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3])));
      G__setnull(result7);
      break;
   case 3:
      DiffJetXFCalcRun17(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      DiffJetXFCalcRun17(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      DiffJetXFCalcRun17(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2289(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      DiffJetGetRunList(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      DiffJetGetRunList(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      DiffJetGetRunList(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2290(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      AnRunDiffJetTreeMakerGetBBC(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), (Bool_t) G__int(libp->para[3]));
      G__setnull(result7);
      break;
   case 3:
      AnRunDiffJetTreeMakerGetBBC(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      AnRunDiffJetTreeMakerGetBBC(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      AnRunDiffJetTreeMakerGetBBC(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   case 0:
      AnRunDiffJetTreeMakerGetBBC();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2291(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      AnRunDiffJetTreeMakerrun17RPFMS(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), (Bool_t) G__int(libp->para[3]));
      G__setnull(result7);
      break;
   case 3:
      AnRunDiffJetTreeMakerrun17RPFMS(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      AnRunDiffJetTreeMakerrun17RPFMS(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      AnRunDiffJetTreeMakerrun17RPFMS(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   case 0:
      AnRunDiffJetTreeMakerrun17RPFMS();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2292(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      DiffJetRPFMSCorr(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3])));
      G__setnull(result7);
      break;
   case 3:
      DiffJetRPFMSCorr(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      DiffJetRPFMSCorr(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      DiffJetRPFMSCorr(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2293(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      DiffJetAnaTreeQaRun17(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      DiffJetAnaTreeQaRun17(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      DiffJetAnaTreeQaRun17(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2294(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      DiffJetXFANCalc_4pt(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3])));
      G__setnull(result7);
      break;
   case 3:
      DiffJetXFANCalc_4pt(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      DiffJetXFANCalc_4pt(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      DiffJetXFANCalc_4pt(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2295(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      AnRunEEMCpi0RpTreeMaker(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, (Bool_t) G__int(libp->para[2]), (Int_t) G__int(libp->para[3]));
      G__setnull(result7);
      break;
   case 3:
      AnRunEEMCpi0RpTreeMaker(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, (Bool_t) G__int(libp->para[2]));
      G__setnull(result7);
      break;
   case 2:
      AnRunEEMCpi0RpTreeMaker(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      AnRunEEMCpi0RpTreeMaker(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   case 0:
      AnRunEEMCpi0RpTreeMaker();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2296(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      DiffJetXFANCalc_12np_5pt(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3])));
      G__setnull(result7);
      break;
   case 3:
      DiffJetXFANCalc_12np_5pt(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      DiffJetXFANCalc_12np_5pt(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      DiffJetXFANCalc_12np_5pt(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2297(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      AnRunDiffJetTreeMaker(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), (Bool_t) G__int(libp->para[3]));
      G__setnull(result7);
      break;
   case 3:
      AnRunDiffJetTreeMaker(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      AnRunDiffJetTreeMaker(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      AnRunDiffJetTreeMaker(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   case 0:
      AnRunDiffJetTreeMaker();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2298(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      DiffJetAnaTreeQa(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      DiffJetAnaTreeQa(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      DiffJetAnaTreeQa(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2299(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      DiffJetXFANCalc_12np_4pt_bkg(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3])));
      G__setnull(result7);
      break;
   case 3:
      DiffJetXFANCalc_12np_4pt_bkg(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      DiffJetXFANCalc_12np_4pt_bkg(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      DiffJetXFANCalc_12np_4pt_bkg(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2300(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      AnRunFmsPi0RpTreeMaker(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      AnRunFmsPi0RpTreeMaker(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2301(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      DiffJetXFANCalc_12np_7pt(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3])));
      G__setnull(result7);
      break;
   case 3:
      DiffJetXFANCalc_12np_7pt(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      DiffJetXFANCalc_12np_7pt(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      DiffJetXFANCalc_12np_7pt(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2302(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      DiffJetXFANCalc_4pt_bkg(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3])));
      G__setnull(result7);
      break;
   case 3:
      DiffJetXFANCalc_4pt_bkg(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      DiffJetXFANCalc_4pt_bkg(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      DiffJetXFANCalc_4pt_bkg(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2303(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      DiffJetXFANCalc(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3])));
      G__setnull(result7);
      break;
   case 3:
      DiffJetXFANCalc(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      DiffJetXFANCalc(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      DiffJetXFANCalc(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2304(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      DiffJetRpCheck((Int_t) G__int(libp->para[0]), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      DiffJetRpCheck((Int_t) G__int(libp->para[0]), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      DiffJetRpCheck((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2305(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      AnRunDiffJetTreeMakerrun17RPEEMC(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), (Bool_t) G__int(libp->para[3]));
      G__setnull(result7);
      break;
   case 3:
      AnRunDiffJetTreeMakerrun17RPEEMC(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      AnRunDiffJetTreeMakerrun17RPEEMC(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      AnRunDiffJetTreeMakerrun17RPEEMC(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   case 0:
      AnRunDiffJetTreeMakerrun17RPEEMC();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2306(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      DiffJetXFCalc(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3])));
      G__setnull(result7);
      break;
   case 3:
      DiffJetXFCalc(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      DiffJetXFCalc(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      DiffJetXFCalc(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2307(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      DiffJetXFANCalc_5pt(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3])));
      G__setnull(result7);
      break;
   case 3:
      DiffJetXFANCalc_5pt(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      DiffJetXFANCalc_5pt(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      DiffJetXFANCalc_5pt(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2308(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      DiffJetXFANCalc_12np_4pt(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3])));
      G__setnull(result7);
      break;
   case 3:
      DiffJetXFANCalc_12np_4pt(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      DiffJetXFANCalc_12np_4pt(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      DiffJetXFANCalc_12np_4pt(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libDiffAnalysis_Dict__0_2309(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      AnRun17RPTreeMaker(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      AnRun17RPTreeMaker(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}


/*********************************************************
* Member function Stub
*********************************************************/

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfunclibDiffAnalysis_Dict {
 public:
  G__Sizep2memfunclibDiffAnalysis_Dict(): p(&G__Sizep2memfunclibDiffAnalysis_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfunclibDiffAnalysis_Dict::*p)();
};

size_t G__get_sizep2memfunclibDiffAnalysis_Dict()
{
  G__Sizep2memfunclibDiffAnalysis_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancelibDiffAnalysis_Dict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablelibDiffAnalysis_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__libDiffAnalysis_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */
extern "C" void G__cpp_setup_memvarlibDiffAnalysis_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/

/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfunclibDiffAnalysis_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globallibDiffAnalysis_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
   G__memfunc_setup("DiffJetXFCalcRun17_WestRP", 2286, G__libDiffAnalysis_Dict__0_2286, 121, -1, -1, 0, 4, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 '\"DiffJetXFPlot.root\"' outName "
"u 'TString' - 0 '\"AN\"' mode u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("AnRunDiffJetTreeMakerrun17RPFMS_zerobias", 3843, G__libDiffAnalysis_Dict__0_2287, 121, -1, -1, 0, 5, 1, 1, 0, 
"u 'TString' - 0 '\"./inFiles_fms.list\"' inFile u 'TString' - 0 '\"jets.root\"' outFile "
"u 'TString' - 0 '\"fms\"' det u 'TString' - 0 '\"fms\"' stream "
"g - 'Bool_t' 0 'kFALSE' isMC", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("DiffJetXFCalcRun17", 1610, G__libDiffAnalysis_Dict__0_2288, 121, -1, -1, 0, 4, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 '\"DiffJetXFPlot.root\"' outName "
"u 'TString' - 0 '\"AN\"' mode u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("DiffJetGetRunList", 1677, G__libDiffAnalysis_Dict__0_2289, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 '\"RunList.txt\"' outName "
"u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("AnRunDiffJetTreeMakerGetBBC", 2535, G__libDiffAnalysis_Dict__0_2290, 121, -1, -1, 0, 4, 1, 1, 0, 
"u 'TString' - 0 '\"./inFiles_fms.list\"' inFile u 'TString' - 0 '\"jets.root\"' outFile "
"u 'TString' - 0 '\"fms\"' det g - 'Bool_t' 0 'kFALSE' isMC", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("AnRunDiffJetTreeMakerrun17RPFMS", 2885, G__libDiffAnalysis_Dict__0_2291, 121, -1, -1, 0, 4, 1, 1, 0, 
"u 'TString' - 0 '\"./inFiles_fms.list\"' inFile u 'TString' - 0 '\"jets.root\"' outFile "
"u 'TString' - 0 '\"fms\"' det g - 'Bool_t' 0 'kFALSE' isMC", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("DiffJetRPFMSCorr", 1466, G__libDiffAnalysis_Dict__0_2292, 121, -1, -1, 0, 4, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 '\"DiffJetXFPlot.root\"' outName "
"u 'TString' - 0 '\"AN\"' mode u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("DiffJetAnaTreeQaRun17", 1931, G__libDiffAnalysis_Dict__0_2293, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 '\"DiffJetAnaQa.root\"' outName "
"u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("DiffJetXFANCalc_4pt", 1715, G__libDiffAnalysis_Dict__0_2294, 121, -1, -1, 0, 4, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 '\"DiffJetXFANCalc_4pt.root\"' outName "
"u 'TString' - 0 '\"DiffJetXFANCalc_4pt.txt\"' outNameText u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("AnRunEEMCpi0RpTreeMaker", 2121, G__libDiffAnalysis_Dict__0_2295, 121, -1, -1, 0, 4, 1, 1, 0, 
"u 'TString' - 0 '\"root://xrdstar.rcf.bnl.gov:1095//home/starlib/home/starreco/reco/production_pp200trans_2015/ReversedFullField/P16id/2015/072/16072047/st_physics_16072047_raw_1000014.MuDst.root\"' fileList u 'TString' - 0 '\"NanoDst.root\"' outFile "
"g - 'Bool_t' 0 'false' showMsg i - 'Int_t' 0 '-1' maxEvents", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("DiffJetXFANCalc_12np_5pt", 2132, G__libDiffAnalysis_Dict__0_2296, 121, -1, -1, 0, 4, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 '\"DiffJetXFANCalc_12np_5pt.root\"' outName "
"u 'TString' - 0 '\"DiffJetXFANCalc_12np_5pt.txt\"' outNameText u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("AnRunDiffJetTreeMaker", 2048, G__libDiffAnalysis_Dict__0_2297, 121, -1, -1, 0, 4, 1, 1, 0, 
"u 'TString' - 0 '\"./inFiles_fms.list\"' inFile u 'TString' - 0 '\"jets.root\"' outFile "
"u 'TString' - 0 '\"fms\"' det g - 'Bool_t' 0 'kFALSE' isMC", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("DiffJetAnaTreeQa", 1518, G__libDiffAnalysis_Dict__0_2298, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 '\"DiffJetAnaQa.root\"' outName "
"u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("DiffJetXFANCalc_12np_4pt_bkg", 2534, G__libDiffAnalysis_Dict__0_2299, 121, -1, -1, 0, 4, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 '\"DiffJetXFANCalc_12np_4pt_bkg.root\"' outName "
"u 'TString' - 0 '\"DiffJetXFANCalc_12np_4pt_bkg.txt\"' outNameText u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("AnRunFmsPi0RpTreeMaker", 2101, G__libDiffAnalysis_Dict__0_2300, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TString' - 0 - fileList u 'TString' - 0 '\"FmsRpTree.root\"' outFile", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("DiffJetXFANCalc_12np_7pt", 2134, G__libDiffAnalysis_Dict__0_2301, 121, -1, -1, 0, 4, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 '\"DiffJetXFANCalc_12np_7pt.root\"' outName "
"u 'TString' - 0 '\"DiffJetXFANCalc_12np_7pt.txt\"' outNameText u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("DiffJetXFANCalc_4pt_bkg", 2118, G__libDiffAnalysis_Dict__0_2302, 121, -1, -1, 0, 4, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 '\"DiffJetXFANCalc_4pt_bkg.root\"' outName "
"u 'TString' - 0 '\"DiffJetXFANCalc_4pt_bkg.txt\"' outNameText u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("DiffJetXFANCalc", 1340, G__libDiffAnalysis_Dict__0_2303, 121, -1, -1, 0, 4, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 '\"DiffJetXFANCalc.root\"' outName "
"u 'TString' - 0 '\"DiffJetXFANCalc.txt\"' outNameText u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("DiffJetRpCheck", 1340, G__libDiffAnalysis_Dict__0_2304, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - 'Int_t' 0 - runNo u 'TString' - 0 '\"DiffJetAnaQa.root\"' outName "
"u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("AnRunDiffJetTreeMakerrun17RPEEMC", 2937, G__libDiffAnalysis_Dict__0_2305, 121, -1, -1, 0, 4, 1, 1, 0, 
"u 'TString' - 0 '\"./inFiles_fms.list\"' inFile u 'TString' - 0 '\"jets.root\"' outFile "
"u 'TString' - 0 '\"eemc\"' det g - 'Bool_t' 0 'kFALSE' isMC", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("DiffJetXFCalc", 1197, G__libDiffAnalysis_Dict__0_2306, 121, -1, -1, 0, 4, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 '\"DiffJetXFPlot.root\"' outName "
"u 'TString' - 0 '\"AN\"' mode u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("DiffJetXFANCalc_5pt", 1716, G__libDiffAnalysis_Dict__0_2307, 121, -1, -1, 0, 4, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 '\"DiffJetXFANCalc_5pt.root\"' outName "
"u 'TString' - 0 '\"DiffJetXFANCalc_5pt.txt\"' outNameText u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("DiffJetXFANCalc_12np_4pt", 2131, G__libDiffAnalysis_Dict__0_2308, 121, -1, -1, 0, 4, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 '\"DiffJetXFANCalc_12np_4pt.root\"' outName "
"u 'TString' - 0 '\"DiffJetXFANCalc_12np_4pt.txt\"' outNameText u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("AnRun17RPTreeMaker", 1646, G__libDiffAnalysis_Dict__0_2309, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TString' - 0 - fileList u 'TString' - 0 '\"FmsRpTree.root\"' outFile", (char*) NULL
, (void*) NULL, 0);

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funclibDiffAnalysis_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__libDiffAnalysis_DictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__libDiffAnalysis_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__libDiffAnalysis_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__libDiffAnalysis_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__libDiffAnalysis_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablelibDiffAnalysis_Dict() {
  G__libDiffAnalysis_DictLN_TString.tagnum = -1 ;
  G__libDiffAnalysis_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__libDiffAnalysis_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__libDiffAnalysis_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__libDiffAnalysis_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablelibDiffAnalysis_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__libDiffAnalysis_DictLN_TString);
   G__get_linked_tagnum_fwd(&G__libDiffAnalysis_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__libDiffAnalysis_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__libDiffAnalysis_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__libDiffAnalysis_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setuplibDiffAnalysis_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setuplibDiffAnalysis_Dict()");
  G__set_cpp_environmentlibDiffAnalysis_Dict();
  G__cpp_setup_tagtablelibDiffAnalysis_Dict();

  G__cpp_setup_inheritancelibDiffAnalysis_Dict();

  G__cpp_setup_typetablelibDiffAnalysis_Dict();

  G__cpp_setup_memvarlibDiffAnalysis_Dict();

  G__cpp_setup_memfunclibDiffAnalysis_Dict();
  G__cpp_setup_globallibDiffAnalysis_Dict();
  G__cpp_setup_funclibDiffAnalysis_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfunclibDiffAnalysis_Dict();
  return;
}
class G__cpp_setup_initlibDiffAnalysis_Dict {
  public:
    G__cpp_setup_initlibDiffAnalysis_Dict() { G__add_setup_func("libDiffAnalysis_Dict",(G__incsetup)(&G__cpp_setuplibDiffAnalysis_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initlibDiffAnalysis_Dict() { G__remove_setup_func("libDiffAnalysis_Dict"); }
};
G__cpp_setup_initlibDiffAnalysis_Dict G__cpp_setup_initializerlibDiffAnalysis_Dict;

