/********************************************************************
* libStarSim_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error libStarSim_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablelibStarSim_Dict();
extern void G__cpp_setup_inheritancelibStarSim_Dict();
extern void G__cpp_setup_typetablelibStarSim_Dict();
extern void G__cpp_setup_memvarlibStarSim_Dict();
extern void G__cpp_setup_globallibStarSim_Dict();
extern void G__cpp_setup_memfunclibStarSim_Dict();
extern void G__cpp_setup_funclibStarSim_Dict();
extern void G__set_cpp_environmentlibStarSim_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./FmsSimRunStarsimAndBfc.h"
#include "./RunFmsJetFinderPro.h"
#include "./FmsSimParticleCheck.h"
#include "./FmsSimMakeResponseMatrix.h"
#include "./FmsSimJetQa.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__libStarSim_DictLN_TString;
extern G__linked_taginfo G__libStarSim_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__libStarSim_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libStarSim_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__libStarSim_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
